export type FundingType =
  | "Pre-Seed"
  | "Seed"
  | "Series A"
  | "Series B"
  | "Series C"
  | "Corporate Round"
  | "Private Equity";

export type InvestmentStatus = "Active" | "Exited" | "Written Off" | "Pending";

export interface InvestmentRound {
  id: string;
  transactionName: string;
  organizationName: string;
  industry: string;
  fundingType: FundingType;
  checkSize: number | null;
  totalRoundSize: number | null;
  announcedDate: string; // ISO "YYYY-MM-DD"
  location: string;
  status: InvestmentStatus;
  initials: string;
  avatarColor: string;
}

export const investments: InvestmentRound[] = [
  {
    id: "1",
    transactionName: "Series A – NovaMed AI",
    organizationName: "NovaMed AI",
    industry: "HealthTech",
    fundingType: "Series A",
    checkSize: 500_000,
    totalRoundSize: 14_000_000,
    announcedDate: "2026-04-10",
    location: "Singapore",
    status: "Active",
    initials: "NM",
    avatarColor: "from-blue-500 to-cyan-500",
  },
  {
    id: "2",
    transactionName: "Seed Round – LoopCart",
    organizationName: "LoopCart",
    industry: "E-Commerce",
    fundingType: "Seed",
    checkSize: 250_000,
    totalRoundSize: 3_500_000,
    announcedDate: "2026-03-15",
    location: "Bengaluru, India",
    status: "Pending",
    initials: "LC",
    avatarColor: "from-violet-500 to-purple-500",
  },
  {
    id: "3",
    transactionName: "Series B – Arable",
    organizationName: "Arable",
    industry: "AgriTech",
    fundingType: "Series B",
    checkSize: 1_000_000,
    totalRoundSize: 20_000_000,
    announcedDate: "2026-02-20",
    location: "San Francisco, USA",
    status: "Active",
    initials: "AR",
    avatarColor: "from-emerald-500 to-teal-500",
  },
  {
    id: "4",
    transactionName: "Series C – Dialpad",
    organizationName: "Dialpad",
    industry: "SaaS",
    fundingType: "Series C",
    checkSize: 2_000_000,
    totalRoundSize: 100_000_000,
    announcedDate: "2025-12-15",
    location: "San Francisco, USA",
    status: "Exited",
    initials: "DP",
    avatarColor: "from-blue-600 to-indigo-600",
  },
  {
    id: "5",
    transactionName: "Series A – Onfleet",
    organizationName: "Onfleet",
    industry: "Logistics",
    fundingType: "Series A",
    checkSize: 750_000,
    totalRoundSize: 14_000_000,
    announcedDate: "2025-11-30",
    location: "San Francisco, USA",
    status: "Active",
    initials: "OF",
    avatarColor: "from-orange-500 to-amber-500",
  },
  {
    id: "6",
    transactionName: "Seed Round – SINAI",
    organizationName: "SINAI",
    industry: "ClimaTech",
    fundingType: "Seed",
    checkSize: 300_000,
    totalRoundSize: 3_800_000,
    announcedDate: "2025-10-28",
    location: "San Francisco, USA",
    status: "Active",
    initials: "SI",
    avatarColor: "from-green-500 to-emerald-500",
  },
  {
    id: "7",
    transactionName: "Series B – Odaseva",
    organizationName: "Odaseva",
    industry: "Data Security",
    fundingType: "Series B",
    checkSize: 1_200_000,
    totalRoundSize: 25_000_000,
    announcedDate: "2026-01-05",
    location: "Paris, France",
    status: "Active",
    initials: "OD",
    avatarColor: "from-rose-500 to-pink-500",
  },
  {
    id: "8",
    transactionName: "Series B – Chargebee",
    organizationName: "Chargebee",
    industry: "FinTech",
    fundingType: "Series B",
    checkSize: 3_000_000,
    totalRoundSize: 55_000_000,
    announcedDate: "2025-09-06",
    location: "San Francisco, USA",
    status: "Exited",
    initials: "CB",
    avatarColor: "from-amber-500 to-yellow-500",
  },
  {
    id: "9",
    transactionName: "Seed Round – SKAEL",
    organizationName: "SKAEL",
    industry: "AI/ML",
    fundingType: "Seed",
    checkSize: 200_000,
    totalRoundSize: 4_100_000,
    announcedDate: "2025-08-29",
    location: "San Francisco, USA",
    status: "Written Off",
    initials: "SK",
    avatarColor: "from-slate-500 to-slate-600",
  },
  {
    id: "10",
    transactionName: "Series A – Pulley",
    organizationName: "Pulley",
    industry: "LegalTech",
    fundingType: "Series A",
    checkSize: 500_000,
    totalRoundSize: 10_000_000,
    announcedDate: "2026-04-01",
    location: "San Francisco, USA",
    status: "Active",
    initials: "PL",
    avatarColor: "from-cyan-500 to-blue-500",
  },
  {
    id: "11",
    transactionName: "Seed Round – Mozart Data",
    organizationName: "Mozart Data",
    industry: "Data & Analytics",
    fundingType: "Seed",
    checkSize: 250_000,
    totalRoundSize: 4_000_000,
    announcedDate: "2026-03-05",
    location: "San Francisco, USA",
    status: "Active",
    initials: "MD",
    avatarColor: "from-purple-500 to-violet-500",
  },
  {
    id: "12",
    transactionName: "Seed Round – Verifiable",
    organizationName: "Verifiable",
    industry: "HealthTech",
    fundingType: "Seed",
    checkSize: 300_000,
    totalRoundSize: 3_000_000,
    announcedDate: "2025-11-20",
    location: "Austin, USA",
    status: "Active",
    initials: "VR",
    avatarColor: "from-teal-500 to-cyan-500",
  },
  {
    id: "13",
    transactionName: "Seed Round – Rune Labs",
    organizationName: "Rune Labs",
    industry: "NeuroTech",
    fundingType: "Seed",
    checkSize: 400_000,
    totalRoundSize: 5_000_000,
    announcedDate: "2026-02-01",
    location: "San Francisco, USA",
    status: "Active",
    initials: "RL",
    avatarColor: "from-indigo-500 to-blue-500",
  },
  {
    id: "14",
    transactionName: "Series B – Extend",
    organizationName: "Extend",
    industry: "FinTech",
    fundingType: "Series B",
    checkSize: 800_000,
    totalRoundSize: 40_000_000,
    announcedDate: "2026-04-03",
    location: "New York, USA",
    status: "Active",
    initials: "EX",
    avatarColor: "from-fuchsia-500 to-pink-500",
  },
];
